# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(886, 591)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 931, 601))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Q4dk76.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(540, 70, 311, 351))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("tumblr_f53b91de9f65c95075743d91ac3e88a6_05684cfa_500.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(360, 10, 181, 51))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(-190, 50, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(0, 130, 311, 241))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("6ba174bf48e9b6dc8d8bd19d13c9caa9.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(40, 10, 201, 111))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("giphy.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(0, 430, 901, 171))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("mountains-dark-landscape-long-exposure-wallpaper-preview.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(300, 90, 281, 251))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("e1cd037aff34ae3aca86e0c6b68b0a2d.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 430, 731, 131))
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit.setDocumentTitle("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(0, 560, 731, 31))
        self.lineEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(650, 560, 81, 31))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 530, 81, 31))
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 0));\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"Segoe Print\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(10, 140, 271, 221))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("spinner.mov.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(30, 150, 261, 211))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("tenor (1).gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=Form)
        self.label_11.setGeometry(QtCore.QRect(30, 150, 261, 211))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("9fa9ec5acda96e7a60321cff300d093f.gif"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">FOXXY AI</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "TextLabel"))
        self.plainTextEdit.setPlainText(_translate("Form", ""))
        self.lineEdit.setText(_translate("Form", "You can type here..."))
        self.pushButton.setText(_translate("Form", "ENTER"))
        self.pushButton_2.setText(_translate("Form", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
